version: '3'
services:
  directus:
    image: directus/directus
    ports:
      - 8055:8055
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'postgres'
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: 'false'
      DB_SSL_REJECT_UNAUTHORIZED: 'false'
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: directus
    volumes:
      - ./data:/var/lib/postgresql/data
