name: Renovate
on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Labels
        run: |
          npm install -g github-label-sync
          github-label-sync --access-token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.json ${{ github.repository }}

      - name: Renovate
        uses: renovatebot/github-action@v39.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'debug'
