name: Renovate
on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sundays
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions: # Add explicit permissions
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install github-label-sync
        run: npm install -g github-label-sync
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Labels
        run: |
          github-label-sync \
            --access-token ${{ secrets.GITHUB_TOKEN }} \
            --labels .github/labels.json \
            ${{ github.repository }}
        continue-on-error: true

      - name: Renovate
        uses: renovatebot/github-action@v39.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: "debug"
